### ISSUE TITLE
the time is displayed incorrectly

### ISSUE THREAD

**Issue by kitkazak** [muan/site#25]
I think it should be 00:16 not 24:16

![image](https://user-images.githubusercontent.com/48328851/164914386-bcdd17e3-8d26-44b1-9b4c-8b134845d89e.png)

**Comment by muan** [comment]
ohhh I'm using `Intl` and it should follow your machines local formatting. this is likely a bug in the browser. can you share what browser/OS you're using?

**Comment by kitkazak** [comment]
I use last ver. of google chrome (which is 100.0.4896.127) and windows 11 ver. 21H2

![image](https://user-images.githubusercontent.com/48328851/164943745-d8de4a0a-7fcc-4f8f-80f3-56c289277b82.png)
![image](https://user-images.githubusercontent.com/48328851/164943763-6a2782b9-7e54-4a0e-8901-0058e70058e6.png)

sorry for russian letters (‘-’*)

**Comment by muan** [comment]
Looks like it's indeed [a bug in Chrome](https://bugs.chromium.org/p/chromium/issues/detail?id=1262801). I added 923a018 as a temporary fix. I've subscribed to the issue and will remove the hack once that's resolved. 

Thanks again for reporting.
