### ISSUE TITLE
Enhance look 

### ISSUE THREAD

**Issue by Keerthivardhan1** [muan/site#32]
website is nice and clean .its seems that you like to keep your site more classic and clean.

Enhance look .
1.  I think it will look more classic if we add any background image or light color  combination. and motion effects 
2.  MODIFYING THE LINKS ( removing text color(color) , removing underline )

**Comment by muan** [comment]
I disagree.

Underlining links is also a basic accessibility requirement. 

https://twitter.com/muanchiou/status/1520981379084824577?s=20&t=xdrvgLbDOIL4kkve8ytiyg
