### ISSUE TITLE
/photos like button does not change on click

### ISSUE THREAD

**Issue by kitkazak** [muan/site#42]
Hi! I noticed something while browsing [muan.co/photos](https://muan.co/photos)

Apparently "Like?" button should be changed to "Liked ♥︎." after being clicked but it does not. At least in Chrome v109.0.5414.120
The site is pretty cool by the way, I'm kinda fan of yours lol

<img src="https://user-images.githubusercontent.com/48328851/216785880-bf8470b3-f3f4-4187-891b-ddc3a229b63d.png" width=75% height=75%>

**Comment by muan** [comment]
Thank you!

I can't seem to reproduce this issue though. Any more cues?

**Comment by kitkazak** [comment]
Actually it seems to be working well now... have no idea why it didn't before. Probably i misunderstood something or was impatient and clicked that button too much.
I'm sorry to have bothered you

**Comment by muan** [comment]
No worries! there may have been a network error that was just dropped or something. I'll look into error handling.
