### ISSUE TITLE
thank you

### ISSUE THREAD

**Issue by ewenme** [muan/site#50]
hi Mu-An, I used your site as a template for my [own](https://ewen.io/) and wanted to say thank you. I've credited you in the `<footer\>` and hope you don't mind my blatant rip-off. looking to grow it into something new and vibrant eventually. would LUV to try out the open heart stuff as well! hope you have a good day today

**Comment by muan** [comment]
That is lovely. Thanks for telling me. Looking forward to see it grow as well!
